In [1]:
!pip install torch

In [2]:
import torch
import numpy as np

# Vector

In [3]:
x = torch.tensor([1, 2, 3])

In [4]:
x[0]

tensor(1)

In [5]:
x.shape[0]

3

In [6]:
x[x.shape[0] - 1]

tensor(3)

In [7]:
x[-1]

tensor(3)

In [8]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7])

In [9]:
x[::2]

tensor([1, 3, 5, 7])

In [10]:
x[1:5:2]

tensor([2, 4])

In [11]:
x[::-1]

ValueError: ignored

# Matrix

In [12]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [13]:
A[2, 1]

tensor(6)

In [14]:
float(A[2, 1])

6.0

In [15]:
A[1:, :1]

tensor([[3],
        [5]])

In [16]:
A[:, 1]

tensor([2, 4, 6])

# Dtype

In [17]:
points = torch.tensor([7, 8, 10, 6.5])

In [18]:
points.dtype

torch.float32

In [19]:
points = torch.tensor([7, 8, 10, 6])
points.dtype

torch.int64

In [20]:
points = torch.tensor([7, 8, 10, 6], dtype=torch.short)
points.dtype

torch.int16

In [21]:
points = torch.tensor([7, 8, 10, 6]).short()
points.dtype

torch.int16

# Transpose

In [22]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [23]:
A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
A_t = A.transpose(0, 1)
A_t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [25]:
A.shape, A_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [26]:
A = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [27]:
A

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [28]:
A.shape

torch.Size([2, 3, 4])

In [29]:
A_t = A.transpose(0, 1)

In [30]:
A_t

tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])

In [31]:
A_t.shape

torch.Size([3, 2, 4])

# Storage

In [32]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [33]:
x.storage()

 1
 2
 3
 4
 5
 6
[torch.LongStorage of size 6]

In [34]:
x[1][2] == x.storage()[5]

tensor(True)

# Tensor metadata: Size, offset, stride

In [35]:
x = torch.tensor([[3, 1, 2], [4, 1, 7]])

In [36]:
x

tensor([[3, 1, 2],
        [4, 1, 7]])

In [37]:
x_t = x.t()

In [38]:
x_t

tensor([[3, 4],
        [1, 1],
        [2, 7]])

In [39]:
id(x.storage()) == id(x_t.storage())

True

In [40]:
x.stride(), x_t.stride()

((3, 1), (1, 3))

# Contiguous Tensors

In [41]:
x.is_contiguous()

True

In [42]:
x_t.is_contiguous()

False

In [43]:
x_t

tensor([[3, 4],
        [1, 1],
        [2, 7]])

In [44]:
x_t_con = x_t.contiguous()

In [45]:
x_t_con

tensor([[3, 4],
        [1, 1],
        [2, 7]])

In [46]:
x_t_con.is_contiguous()

True

In [47]:
x_t.storage()

 3
 1
 2
 4
 1
 7
[torch.LongStorage of size 6]

In [48]:
x_t_con.storage()

 3
 4
 1
 1
 2
 7
[torch.LongStorage of size 6]

# Torch GPU

In [49]:
x_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [50]:
x_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [51]:
x = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
x

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [52]:
x_gpu = x.to(device='cuda')
x_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [53]:
x_cpu = x_gpu.to(device='cpu')
x_cpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [54]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

# Torch to Numpy

In [55]:
x = torch.tensor([1,2,3])

In [56]:
x_np = x.numpy()

In [57]:
x_np

array([1, 2, 3])

In [58]:
x[1] = 0
x, x_np

(tensor([1, 0, 3]), array([1, 0, 3]))

In [59]:
x_np = np.array([1, 2, 3])

In [60]:
x_cpu = torch.from_numpy(x_np)

In [61]:
x_gpu = torch.tensor([1, 2, 3], device='cuda')

In [62]:
x_np = x_gpu.numpy()

TypeError: ignored

In [63]:
x_np = x_gpu.cpu().numpy()

In [64]:
x_np

array([1, 2, 3])

In [65]:
x_gpu[1] = 0

In [66]:
x_gpu, x_np

(tensor([1, 0, 3], device='cuda:0'), array([1, 2, 3]))